version: "3.1"

services:
  mysql:
    image: mariadb
    container_name: mysql-dbs
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: root
  # adminer:
  #   image: adminer
  #   container_name: adminer
  #   ports:
  #     - 8080:8080
volumes:
  mysql:
    driver: local
